
@base = 127.0.0.1:8080

### JSON-错误测试

POST http://{{base}}/login-json?id=12312323&num=2 HTTP/1.1
Content-Type: application/json

{
  "name": "err name",
  "password": "123456"
}

### JSON-正确测试
POST http://{{base}}/login-json?id=12312323&num=2 HTTP/1.1
Content-Type: application/json

{
  "name": "Tony",
  "password": "123456"
}

### Form 测试-失败
POST http://{{base}}/login-form?id=12312323&num=2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=Tony
&password=1234567

### Form 测试-成功
POST http://{{base}}/login-form?id=12312323&num=2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=Tony
&password=123456